/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateEnumerationArgs } from "./CreateEnumerationArgs";
import { UpdateEnumerationArgs } from "./UpdateEnumerationArgs";
import { DeleteEnumerationArgs } from "./DeleteEnumerationArgs";
import { EnumerationFindManyArgs } from "./EnumerationFindManyArgs";
import { EnumerationFindUniqueArgs } from "./EnumerationFindUniqueArgs";
import { Enumeration } from "./Enumeration";
import { EnumerationService } from "../enumeration.service";

@graphql.Resolver(() => Enumeration)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class EnumerationResolverBase {
  constructor(
    protected readonly service: EnumerationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Enumeration",
    action: "read",
    possession: "any",
  })
  async _enumerationsMeta(
    @graphql.Args() args: EnumerationFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Enumeration])
  @nestAccessControl.UseRoles({
    resource: "Enumeration",
    action: "read",
    possession: "any",
  })
  async enumerations(
    @graphql.Args() args: EnumerationFindManyArgs
  ): Promise<Enumeration[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Enumeration, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Enumeration",
    action: "read",
    possession: "own",
  })
  async enumeration(
    @graphql.Args() args: EnumerationFindUniqueArgs
  ): Promise<Enumeration | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Enumeration)
  @nestAccessControl.UseRoles({
    resource: "Enumeration",
    action: "create",
    possession: "any",
  })
  async createEnumeration(
    @graphql.Args() args: CreateEnumerationArgs
  ): Promise<Enumeration> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Enumeration)
  @nestAccessControl.UseRoles({
    resource: "Enumeration",
    action: "update",
    possession: "any",
  })
  async updateEnumeration(
    @graphql.Args() args: UpdateEnumerationArgs
  ): Promise<Enumeration | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Enumeration)
  @nestAccessControl.UseRoles({
    resource: "Enumeration",
    action: "delete",
    possession: "any",
  })
  async deleteEnumeration(
    @graphql.Args() args: DeleteEnumerationArgs
  ): Promise<Enumeration | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
